### ISSUE TITLE
where is proxl-import-xml-to-db?

### ISSUE THREAD

**Issue by wjlong0318** [yeastrc/proxl-web-app#1]
I try to install the proXL,but I couldn't find the proxl-import-xml-to-db program from the link: https://github.com/yeastrc/proxl-import-xml-to-db, can you give me some advice?

**Comment by danjasuw** [comment]
That Github project has been rolled into https://github.com/yeastrc/proxl-web-app.

The Zip file for a release includes all parts of Proxl.
