### ISSUE TITLE
How can I get to spectrum view in the web-app?

### ISSUE THREAD

**Issue by ChengkangLi** [yeastrc/proxl-web-app#16]
Hi, I am importing pLink result into this proxl web app, however, i am not able to find the spectrum view that was mentioned in the documentation page, can anyone give me a hand on it. I am appreciated. 

Bests,
Chengkang

**Comment by mriffle** [comment]
Chengkang, thanks for the question. Did you upload a spectra file (mzML or mzXML) with your proxl XML file? If so, you can find the link for viewing spectra wherever PSMs are listed in the site. For example, on this page: https://www.yeastrc.org/proxl_public/crosslinkProtein.do?projectSearchId=22  If you click on a protein row, it will show a list of peptides. If you click on a peptide, it will show a list of PSMs--each PSM has a "View Spectrum" link for viewing the spectrum.

To upload a mzML/mzXML file with your proxl XML file, see this image below:

![image](https://user-images.githubusercontent.com/4825678/96374167-eba73c80-1125-11eb-9197-bcc2326c54d3.png)

Note the +Add Scan File link. Clicking this will allow you to upload 1 or more spectra file with your proxl XML file, which it will use to show spectra for PSMs in that proxl XML file.

**Comment by ChengkangLi** [comment]
Dear Mr. or Ms. someone,

Thank you so much. Indeed, I did not upload spectra file, but only the .xml file, let’s see what I get after uploading also the scan files.

Best regards,
Chengkang
