### ISSUE TITLE
Data Export function for XiNet successor XiViewer

### ISSUE THREAD

**Issue by talpa25** [yeastrc/proxl-web-app#17]
Dear developer,

thank you very much for your efforts in XL-MS visualization. I wonder whether you might know that XiNet is outdated and got a successor XiViewer https://xiview.org/xiNET_website/index.php Unfortunately the data format changed a bit so the data output of ProXL for XiNet is not compatible with the newer version. It would be very cool if you may provide this data export function capability in future :) 

Best,

Roman

**Comment by mriffle** [comment]
Roman, thanks for letting us know. Took a look at it and looks quite doable, I'll let you know when it's done.

**Comment by mriffle** [comment]
Roman, I just implemented this, you should see an xiVIEW option on the download now. Let me know if you have any trouble!
