### ISSUE TITLE
create db error

### ISSUE THREAD

**Issue by veremchook** [yeastrc/proxl-web-app#4]
Hello,

I'm trying to set up Proxl on Debian 9.3 / MariaDB 10.1.26 and currently at step 3 of this guide:

http://proxl-web-app.readthedocs.io/en/latest/install/intro.html

Issue:

cat create_empty_database.sql | mysql -u root -p
Enter password: 
ERROR 1071 (42000) at line 1954: Specified key was too long; max key length is 767 bytes

The line in question says:

CREATE INDEX url ON url_shortener (url(500) ASC);

Quick Googling pointed me to a InnoDB/UTF8 limitation.
After changing 500 to 255, dropping proxl database and re-running the script it appears to have succeeded.

Is it ok to leave it like that and carry on with the installation?

Please advise.

Thanks
Adam

**Comment by danjasuw** [comment]
A shorter index length is fine.

We test on MySQL 5.7.  
It could be that an older version of MySQL (and it's associated MariaDB versoin) 
has a shorter limit on the max key length.
