### ISSUE TITLE
Installation: Error getting database connection

### ISSUE THREAD

**Issue by aretaon** [yeastrc/proxl-web-app#5]
Hi,

I'm trying to install ProXL 1.7.0 as described [here]( http://proxl-web-app.readthedocs.io/en/latest/install/intro.html). However, when browsing to the webapp, I only get an error stating "There was a problem processing your request."

I found the proxl_generic.errors.log file and it contains the following message as the first error: 
`ERROR 2018-06-21 14:28:46,985 [Thread-5][] org.yeastrc.xlink.www.db_web.DBConnectionFactoryWeb - ERROR: getting database connection: db: proxl`

Can I provide any more information to find the cause of the error?

Thanks in advance for your help!

**Comment by danjasuw** [comment]
Hi,

What is the full call stack for the error you list:
    ERROR 2018-06-21 14:28:46,985 [Thread-5][] 
    org.yeastrc.xlink.www.db_web.DBConnectionFactoryWeb - ERROR: getting database connection: db: proxl

Are you using Tomcat, if yes, what version?
What version of MySQL are you using?

If you are using Tomcat, did you configure the "context.xml" file in the "conf" subdirectory?
Can you share the entry for <Resource     name="jdbc/proxl" ...   Minus the username and password values (or change them to "XXX")

**Comment by aretaon** [comment]
Thanks for the fast reply.

As the full error stack is rather long, you can find the [proxl_generic.errors.log](https://github.com/yeastrc/proxl-web-app/files/2125007/proxl_generic.errors.log) attached.

I'm using Tomcat:
```
Server version: Apache Tomcat/8.5.31
Server built:   Apr 27 2018 20:24:25 UTC
Server number:  8.5.31.0
OS Name:        Linux
OS Version:     4.4.0-128-generic
Architecture:   amd64
JVM Version:    1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11
JVM Vendor:     Oracle Corporation
```
MySQL:
```
mysql  Ver 14.14 Distrib 5.7.22, for Linux (x86_64) using  EditLine wrapper
```
And the context.xml entry:
```
<Resource     name="jdbc/proxl"
                  auth="Container"
                  type="javax.sql.DataSource"
                  factory="org.apache.commons.dbcp.BasicDataSourceFactory"
                  maxActive="100"
                  maxIdle="30"
                  maxWait="10000"
                  username="XXXXX"
                  password="XXXXX"
                  driverClassName="com.mysql.jdbc.Driver"

                  minEvictableIdleTimeMillis="14400000"
                  timeBetweenEvictionRunsMillis="3600000"
                  numTestsPerEvictionRun="100"

                  url="jdbc:mysql://localhost:3306/proxl?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;characterSetResults=UTF-8"/>
```

**Comment by danjasuw** [comment]
In Java, it always pays to scroll down looking for the string "Caused by:"

In your stack trace, I found:

Caused by: com.mysql.cj.exceptions.InvalidConnectionAttributeException: The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.

I have not seen this error and don't have a suggestion for a fix.

**Comment by aretaon** [comment]
Your tip with the "Caused by:" string was great!

The error seems to be caused by a typo in the mysql-connector-java version 5.1.33 - 5.1.37 (mentioned [here](https://stackoverflow.com/questions/26515700/mysql-jdbc-driver-5-1-33-time-zone-issue).
As I'm not experienced enough with mySQL, I used a quick and dirty workaround by changing the url in context.xml to

```
url="jdbc:mysql://localhost:3306/proxl?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;characterSetResults=UTF-8&amp;useLegacyDatetimeCode=false&amp;serverTimezone=UTC"/>
```

mySQL now runs on UTC instead of CEST, but that's okay...
