### ISSUE TITLE
Add support for user-defined cross-linkers to proxl

### ISSUE THREAD

**Issue by mriffle** [yeastrc/proxl-web-app#7]
Moving discussion from MetaMorpheus issue (https://github.com/smith-chem-wisc/MetaMorpheus/issues/1589) to here.

User request: add user-defined linker support to proxl. Collaborate with @Dmorgen to get this nailed down.

**Comment by mriffle** [comment]
We plan on rolling this out in two phases:

**Phase One**: Remove the requirement that proxl already know about the linker referenced in the proxl XML file. When proxl doesn't already know about the specific linker, some minor functionality in proxl will be lost:
   1. Since proxl won't know the linking rules, some peptides may rarely be incorrectly mapped to some proteins. This will happen when  a peptide has a link on one of its termini and the linker can only link to the n- or c-terminus AND there is a protein in the FASTA file that contains this peptide and the peptide isn't at the n- or c-terminus. In this case, the peptide would also be mapped to the protein where it is not terminal, and this would affect the list of reported proteins and the protein coverage display.

   2. The "show linkable positions" option in the proxl graphical displays would not be available.

**Phase Two**: User definable linkers. The proxl XML schema will support user-defined linkers and be populated automatically by converters for respective programs (such as MetaMorpheus, Kojak, and pLink). There would be no loss of functionality.

Phase one should be completed in the next few days, I'll be in touch when it's ready to go. I'll run my thoughts for phase two by you at that time and we can make sure it'll do what you need it to do.

**Comment by Dmorgen** [comment]
Sure, I will be waiting.
Many thanks!

**Comment by mriffle** [comment]
@Dmorgen We've rolled out phase one, which allows users to upload data using cross-linkers we don't have parameters for. You should be able to upload data for any linker. You'll need to use the latest MetaMorpheus Proxl XML converter found here: https://github.com/yeastrc/proxl-import-metamorpheus/releases

Please let me know if you run into any problems.

We're starting on phase two now, which will allow converters (such as the MetaMorpheus one) to submit actual definitions for the parameters of the linker with the experiment, which will provide full functionality for any cross-linker used to search the data (such as viewing linkable positions).

**Comment by Dmorgen** [comment]
@mriffle Hi, I'm trying the new converter, but it still demands the -l command. what should I do?

Thanks!
D.

**Comment by mriffle** [comment]
@Dmorgen You can specify the name of any linker you want with the -l parameter. Just specify whatever string you want to show up in proxl when it tells you what cross-linker you used in that search.

Going forward, I should probably remove the need to supply a name and just read it from the toml file. But in the meantime, you can supply any name you want.

**Comment by Dmorgen** [comment]
Thanks!

D.

**Comment by Dmorgen** [comment]
@mriffle It works! Awesome!

**Comment by mriffle** [comment]
@Dmorgen FYI, we've finished the full roll-out of this feature.

Whichever positions are linkable, as defined in the config file for the search, will be captured in the proxl XML file and used by proxl when needing to show linkable positions. So, any linker you can configure for MetaMorpheus should be fully supported.

Also, you no longer need to supply the -l parameter for the MetaMorpheus converter, unless you want to override the name that shows up for that cross-linker in proxl.
