### ISSUE TITLE
error: running the import manager process

### ISSUE THREAD

**Issue by heejongkim** [yeastrc/proxl-web-app#8]
Hi,

Thank you for sharing the excellent software for the public.
As I've tackled down the installation, I got stuck with the following msg at the end of the installation steps.

# java -jar runImportProxlXML.jar -c=run_importer_config_file.properties
Exception in thread "main" java.lang.ClassNotFoundException: org.yeastrc.proxl.import_xml_to_db_runner_pgm.program.ImporterRunnerProgram
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:415)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)

I feel like I'm missing something obvious but I don't think I can see it at this moment.
Can you please give me some insights on this to execute the import manager process?

Thank you so much.

best,
hee jong kim

**Comment by danjasuw** [comment]
Hi,

Is this from the last release or did was the GIT repo cloned and built?

Can you add the file(s) you are trying to run to this issue?

If building the repo, I recommend to build the whole repo by running an ant script at the root of the repo.
This will require that ant, gradle, and npm be installed.
We are using the latest ant, gradle 4.x, and latest npm.
Before running the ant script, copy the file 'aa_ant__build_all_proxl_config.properties_Sample' to 'aa_ant__build_all_proxl_config.properties' and update it with the paths to gradle and npm.
Then run the ant script 'ant__build_all_proxl.xml' using the command 'ant -f ant__build_all_proxl.xml'.
The results will be in the 'deploy' subdirectory.
The importer and run importer will be runnable jar files that can be run using 'java -jar <jar filename>'.
Optional parameters would be for max heap.
For Run Importer, the max heap can be pretty low like ' -Xms256m -Xmx512m '.

Please let me know if you  need more help.

Dan J.

**Comment by danjasuw** [comment]
Hi,

Is this on Linux, Windows, or Mac, or something else?

I checked the contents of runImportProxlXML.jar from our build and the class is in it.
We use the runnable jar runImportProxlXML.jar directly from the ant build runnable jar so I am not sure why it isn't working.
Having the jar you built for review should help.

Dan J

**Comment by heejongkim** [comment]
Hi,
thank you for super-fast response.
It's on Windows.
I used the last release instead of building it from the repository.
As you recommended, I lowered the max heap and still got the same msg like the following:

# java -jar -Xmx512m runImportProxlXML.jar -c=run_importer_config_file.properties
Exception in thread "main" java.lang.ClassNotFoundException: org.yeastrc.proxl.import_xml_to_db_runner_pgm.program.ImporterRunnerProgram
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:415)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)

Thanks.

hee jong

**Comment by danjasuw** [comment]
Hi,

What version of Windows?  What edition of Windows?

What version of Java?
can you run 'java -version' and post the result?

I downloaded the release V1.7.0 (zip file proxl_deploy_V1.7.0.zip) to Windows 10 and using Oracle Java 8 it ran fine.
I checked the jar for the main class and it is in there.

I cannot see any reason for the error you are getting.

**Comment by heejongkim** [comment]
Hi,

It's under windows server 2016.
# java -version
java version "12.0.1" 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

all the installation prior to this went ok and I can access to the website.
Maybe the java version is too high?
thanks.

**Comment by danjasuw** [comment]
Hi,

I am able to replicate the problem with Java 12.
I will be fixing the runnable jars to work with Java 12.
It will be up in the near future, definitely by Tuesday.

I will be creating a new release of Proxl after the fix.
There will be no migration script so you will have to delete the database and start over.
There are too many database changes.

Let me know if you plan on importing scan files (mzML or mzXML).
Proxl now uses our other application 'Spectral Storage Service' at https://github.com/yeastrc/Spectral_Storage_Service.
I haven't created a release for that yet.

**Comment by heejongkim** [comment]
Thanks for the follow up on this.
I didn't realize that there's a big gap between the last release and the current nightly version.
I haven't started adding anything yet so it won't be a migration issue.

Yes, I'm planning on importing the mzML files since I want to use this as a primary organizer to keep track of experiments and collaborations.
If you can help me out for that, it would be great.

So, besides this importing java tool, this Spectral Storage Service should be up and running concurrently?

Many thanks!

best,
hee jong

**Comment by danjasuw** [comment]
Hi,

After further work to support java 9+, it is determined that it will take longer than I have time for at the moment.  I may be able to get back to this in a couple weeks.  
For now, the option is to use Java 8.
If you want to move ahead with that plan, let me know and I will create a new release so you have the latest version.  I can also at that point come up with instructions for Spectral Storage.

Dan J

**Comment by heejongkim** [comment]
Hi Dan,

yes. I can go with java 8. If you can tell me the exact version, I can install the right version.
Do you anticipate that it's possible to upgrade from this release to the newer versions from now?

If you can guide me for the entire installation, that would be awesome.

Thank you so much.

best,
hee jong

**Comment by danjasuw** [comment]
If by "this release" you mean the release you installed of Proxl, then no it won't be possible to upgrade to the latest release, primarily since scan data is now stored in Spectral Storage and there is no conversion to move it there.  There were a lot of other changes to the database.

As to which Java to install, the latest edition of Java 8 should be fine.  If there is an openJDK version, that should be fine, although we developed on and run Oracle Java 8.

I generated a new release of Proxl today.
https://github.com/yeastrc/proxl-web-app/releases/tag/V2.0.0

It may be Wednesday end of day or end of week before I can generate a release of Spectral Storage.
https://github.com/yeastrc/Spectral_Storage_Service
Do not use the current release of Spectral Storage.  It is just a placeholder.

**Comment by heejongkim** [comment]
Oh sorry for the confusion.
I meant by the upcoming release.

I will wait until all components are available and ready for the installation and, in the meanwhile, I will install the java 8.

Thanks.

best,
hee jong

**Comment by danjasuw** [comment]
Not a problem.  Just wanted to make sure you don't use the V1.7 release since there won't be an upgrade path.

**Comment by heejongkim** [comment]
Hi.
I'd like to follow up on this thread.
Can I use the current release for both this repo and Spectral_Storage_Service to start the installation?

Thanks.

**Comment by danjasuw** [comment]
I have put up a new release.  It should be ready for use.

I will work on a deployable release for 
https://github.com/yeastrc/Spectral_Storage_Service
Please open an issue there for any questions or problems related to Spectral_Storage_Service.

**Comment by heejongkim** [comment]
So, I still need to follow the installation part: 6. Install and configure the import manager?

I'm sorry that I'm still confused what to do and how this app and spectral storage service get orchestrated together.

If you have any installation guide like this app, that would be very helpful to finalize this installation.

Thanks.

**Comment by danjasuw** [comment]
It looks like the installation instructions are out of date.

I would recommend the following for getting up and running:
(The icons have tooltips that have the text that I list)

Log in using the initial user.
In the upper right, click the icon for "Manage Users".
Create a new Admin user.
In the upper right, click the icon for "Logout"

Log in with the new Admin user.
In the upper right, click the icon for "Manage Users".
Click the "X" to the left of initial user to disable it.

In the upper right, click the gear icon for "Manage Proxl Configuration"
Spectral Storage URL is configured here
If the Spectral Storage Service .war files are placed in the same webapp container use:
(assuming web app container is at port 8080)
http://127.0.0.1:8080/spectral_storage_accept_import
http://127.0.0.1:8080/spectral_storage_get_data

The section under "Submit Search Upload on Website" needs to be configured.

Set "SMTP Server URL for emails sent: " to "localhost" if running a SMTP Server on the same machine.

**Comment by danjasuw** [comment]
For configuring the importer and run_importer,
there are sample configuration files in the zip file under '/proxl_importer/'
Running the importer and run_importer with "-h" will provide command line help.
java -jar importProxlXML.jar -h
java -jar runImportProxlXML.jar -h

**Comment by mriffle** [comment]
Following up on this thread because people might still be interested.

We now officially support installing proxl using Docker and docker-compose. You can bring up all pre-configured components of proxl at once using a single command line statement. The updated installation instructions are here: https://proxl-web-app.readthedocs.io/en/latest/install/intro.html
