### ISSUE TITLE
installation error: insert_initial_user.sql

### ISSUE THREAD

**Issue by heejongkim** [yeastrc/proxl-web-app#9]
Hi,

As I'm trying to install the newest release, I'm getting the following error from insert_initial_user.sql
---------------
Preparing...
Importing insert_initial_user.sql...
Finished executing script
ERROR 1146 (42S02) at line 21: Table 'proxl.user_tbl' doesn't exist
Operation failed with exitcode 1
---------------
Thanks.

**Comment by danjasuw** [comment]
Yes that table doesn't exist in Proxl.  It does exist in Limelight and I may have accidentally copied this insert from that setup SQL.
I will research this error further when I get into the office tomorrow.

For now, if you are able to log in using the user 'initial_user' I would say the setup was successful.

**Comment by heejongkim** [comment]
Yes. I can log in the website.
The only subtle thing that I want to say is that the installation guide says the username is "initial_proxl_user" instead of "initial_user".

Thanks!

**Comment by danjasuw** [comment]
I changed the username back to "initial_proxl_user" .

I removed the failing inserts.
